In [1]:
import pandas as pd
import numpy as np
from keras.layers import Input, Dense, Dropout, BatchNormalization
from keras.models import Model, Sequential

Using TensorFlow backend.


In [2]:
df_train = pd.read_csv('data/train.csv')

X_train = pd.read_csv('train_with_prob.csv', index_col=False)
X_train = X_train.drop('Unnamed: 0', axis=1)
X_train.head()

y_train = df_train['is_duplicate'].values

In [3]:
# Up/down sampling
pos_train = X_train[y_train == 1]
neg_train = X_train[y_train == 0]
X_train = pd.concat((neg_train, pos_train.iloc[:int(0.8 * len(pos_train))],
                     neg_train))
y_train = np.array([0] * neg_train.shape[0] + [1] * pos_train.iloc[:int(
    0.8 * len(pos_train))].shape[0] + [0] * neg_train.shape[0])
print(np.mean(y_train))
del pos_train, neg_train

0.189701079013


In [4]:
X_train.replace(np.inf, 99)
X_train.replace(np.nan, 0)

word_match  tfidf_wm  tfidf_wm_stops   jaccard  wc_diff  wc_ratio  \
0         0.727273  0.796024        0.772164  0.769231        2  0.857143   
1         0.307692  0.359200        0.361758  0.250000        5  1.625000   
2         0.363636  0.302555        0.355191  0.200000        4  0.714286   
3         0.000000  0.000000        0.000000  0.000000        2  0.818182   
4         0.000000  0.034253        0.000000  0.111111        6  0.538462   
6         0.000000  0.000000        0.000000  0.000000        7  2.750000   
8         0.500000  0.476358        0.396755  0.600000        0  1.000000   
9         0.363636  0.483158        0.503203  0.200000        0  1.000000   
10        0.000000  0.009127        0.000000  0.041667       10  2.111111   
14        0.818182  0.827309        0.804625  0.833333        0  1.000000   
17        0.000000  0.013576        0.000000  0.052632        4  0.666667   
19        0.600000  0.525878        0.488021  0.636364        0  1.000000   
21        0.000000  0.013568        0.000000  0.066667        4  1.666667   
22        0.666667  0.608709        0.652711  0.333333        2  0.777778   
23        0.000000  0.000000        0.000000  0.000000        4  1.571429   
24        0.000000  0.000000        0.000000  0.000000        7  0.588235   
25        0.769231  0.785295        0.720855  0.812500        1  1.071429   
26        0.400000  0.370316        0.353365  0.428571        2  1.500000   
27        0.000000  0.000000        0.000000  0.000000        1  0.875000   
28        0.800000  0.759682        0.762706  0.700000        1  1.125000   
30        0.666667  0.665955        0.655016  0.545455        1  0.888889   
33        0.000000  0.003638        0.000000  0.043478        8  0.529412   
34        0.571429  0.426011        0.406653  0.555556        2  0.750000   
35        0.375000  0.250691        0.295487  0.173913        1  1.076923   
36        0.352941  0.304562        0.324324  0.310345        5  0.782609   
37        0.074074  0.129067        0.080532  0.083333       12  1.480000   
39        0.000000  0.029149        0.000000  0.038462        3  0.800000   
40        0.000000  0.000000        0.000000  0.000000        2  1.500000   
41        1.000000  0.985795        1.000000  0.875000        1  0.875000   
42        0.800000  0.775736        0.744603  0.800000        0  1.000000   
...            ...       ...             ...       ...      ...       ...   
404239    0.333333  0.251716        0.207942  0.444444        1  1.166667   
404245    0.500000  0.529330        0.524131  0.285714        3  1.230769   
404246    0.142857  0.183784        0.160514  0.157895        5  1.555556   
404248    0.500000  0.505783        0.513577  0.384615        4  0.636364   
404250    0.181818  0.186608        0.207019  0.052632        5  0.615385   
404251    0.000000  0.006745        0.000000  0.035714       11  0.521739   
404252    0.800000  0.713749        0.728201  0.545455        1  0.888889   
404253    0.250000  0.152207        0.172908  0.066667        2  1.285714   
404254    0.206897  0.298958        0.234273  0.212766       10  1.400000   
404255    0.571429  0.549260        0.524909  0.500000        1  0.800000   
404256    0.545455  0.519524        0.507864  0.421053        7  1.636364   
404260    0.571429  0.271244        0.382804  0.250000        3  1.500000   
404262    0.666667  0.668074        0.668261  0.555556        0  1.000000   
404263    0.333333  0.319812        0.330545  0.222222        0  1.000000   
404264    0.266667  0.241865        0.249702  0.130435        6  0.625000   
404266    0.160000  0.159018        0.166106  0.171429       21  2.750000   
404268    0.000000  0.000000        0.000000  0.000000        4  0.692308   
404269    0.666667  0.685246        0.755497  0.214286        3  1.428571   
404270    0.400000  0.367568        0.228984  0.600000        0  1.000000   
404271    0.000000  0.065389        0.000000  0.043478        1  0.923077   
4042

In [5]:
X_train['q1_q2_freq_diff'] = np.abs(X_train['q1_freq'] - X_train['q2_freq'])
X_train['q1_q2_freq_sum'] = X_train['q1_freq'] + X_train['q2_freq']
X_train['skew_diff'] = np.abs(X_train['skew_q1vec'] - X_train['skew_q2vec'])
X_train['skew_sum'] = X_train['skew_q1vec'] + X_train['skew_q2vec']

In [6]:
X_train.shape

(629464, 180)

In [7]:
X_train.head()

word_match  tfidf_wm  tfidf_wm_stops   jaccard  wc_diff  wc_ratio  \
0    0.727273  0.796024        0.772164  0.769231        2  0.857143   
1    0.307692  0.359200        0.361758  0.250000        5  1.625000   
2    0.363636  0.302555        0.355191  0.200000        4  0.714286   
3    0.000000  0.000000        0.000000  0.000000        2  0.818182   
4    0.000000  0.034253        0.000000  0.111111        6  0.538462   

   wc_diff_unique  wc_ratio_unique  wc_diff_unq_stop  wc_ratio_unique_stop  \
0               1         0.916667                 1              0.833333   
1               4         1.500000                 5              2.250000   
2               4         0.714286                 1              0.833333   
3               1         0.900000                 1              1.250000   
4               6         0.538462                 5              0.500000   

     ...      clf_127   clf_128   clf_129   clf_130   clf_131   clf_132  \
0    ...     0.520313  0.494767  0.641264  0.553826  0.522829  0.442324   
1    ...     0.266175  0.099237  0.176471  0.294340  0.142857  0.491857   
2    ...     0.266175  0.351983  0.292521  0.356969  0.237123  0.352159   
3    ...     0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
4    ...     0.000241  0.000000  0.000000  0.000214  0.000000  0.000000   

   q1_q2_freq_diff  q1_q2_freq_sum  skew_diff  skew_sum  
0                1               3   0.123719 -0.060084  
1                5              11   0.085969  0.103438  
2                1               3   0.095198  0.384306  
3                0               2   0.072176  0.067122  
4                2               4   0.248626 -0.019072  

[5 rows x 180 columns]

In [8]:
# np.unique(y_train[255000:256000])

In [9]:
# X_train, y_train = X_train[255000:256000], y_train[255000:256000]

In [10]:
# Initialize the constructor
model = Sequential()

# Add an input layer 
model.add(Dense(512, activation='relu', input_shape=(180,)))
model.add(BatchNormalization())
model.add(Dropout(0.3))
# Add one hidden layer 
model.add(Dense(512, activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.3))
model.add(Dense(128, activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.3))
# Add an output layer 
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['binary_accuracy'])
# model.fit(data, labels)  # starts training

In [11]:
tr = np.array(X_train)
# tr[np.isnan(tr)] = 0
np.isnan(tr)

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ..., 
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]], dtype=bool)

In [12]:
from sklearn.preprocessing import StandardScaler

In [13]:
scaler = StandardScaler()
scaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [14]:
scaler.transform(tr)

array([[  1.27966051e+00,   1.57460768e+00,   1.42807242e+00, ...,
         -3.38865634e-01,   1.39393754e-01,  -3.63758546e-01],
       [ -2.05478435e-01,  -1.84499121e-02,  -1.30459176e-03, ...,
          1.71699212e-01,  -2.49449948e-01,   3.58643562e-01],
       [ -7.45990850e-03,  -2.25030081e-01,  -2.41743056e-02, ...,
         -3.38865634e-01,  -1.54393281e-01,   1.59944597e+00],
       ..., 
       [  4.75210250e-01,   8.70099094e-01,   1.21856692e+00, ...,
         -4.02686240e-01,  -6.55155371e-01,  -1.60592837e+00],
       [ -1.29458033e+00,  -1.30957601e+00,  -1.26124438e+00, ...,
         -4.02686240e-01,   2.75483603e-01,  -8.67336543e-01],
       [  2.24500083e+00,   2.07289858e+00,   2.22158509e+00, ...,
         -4.02686240e-01,  -1.13496996e+00,   1.56401635e+00]])

In [13]:
# tr = np.array(X_train)
# tr[np.isnan(tr)] = 0
# tr[np.isinf(tr)] = 99
# from sklearn import preprocessing
# tr = preprocessing.scale(tr)
# np.unique(np.isnan(tr)), np.unique(np.isinf(tr))

(array([False], dtype=bool), array([False], dtype=bool))

In [14]:
# from sklearn import preprocessing
# tr = preprocessing.scale(tr)

In [15]:
# tr

array([[  1.27966051e+00,   1.57460768e+00,   1.42807242e+00, ...,
         -3.38865634e-01,   1.39393754e-01,  -3.63758546e-01],
       [ -2.05478435e-01,  -1.84499121e-02,  -1.30459176e-03, ...,
          1.71699212e-01,  -2.49449948e-01,   3.58643562e-01],
       [ -7.45990850e-03,  -2.25030081e-01,  -2.41743056e-02, ...,
         -3.38865634e-01,  -1.54393281e-01,   1.59944597e+00],
       ..., 
       [  4.75210250e-01,   8.70099094e-01,   1.21856692e+00, ...,
         -4.02686240e-01,  -6.55155371e-01,  -1.60592837e+00],
       [ -1.29458033e+00,  -1.30957601e+00,  -1.26124438e+00, ...,
         -4.02686240e-01,   2.75483603e-01,  -8.67336543e-01],
       [  2.24500083e+00,   2.07289858e+00,   2.22158509e+00, ...,
         -4.02686240e-01,  -1.13496996e+00,   1.56401635e+00]])

In [17]:
model.fit(tr, y_train, epochs=30, verbose=2)

Epoch 1/30
 - 204s - loss: 0.1880 - binary_accuracy: 0.9217
Epoch 2/30
 - 202s - loss: 0.1866 - binary_accuracy: 0.9223
Epoch 3/30
 - 209s - loss: 0.1870 - binary_accuracy: 0.9224
Epoch 4/30
 - 211s - loss: 0.1874 - binary_accuracy: 0.9223
Epoch 5/30
 - 210s - loss: 0.1927 - binary_accuracy: 0.9202
Epoch 6/30
 - 210s - loss: 0.1881 - binary_accuracy: 0.9216
Epoch 7/30
 - 214s - loss: 0.1900 - binary_accuracy: 0.9212
Epoch 8/30
 - 215s - loss: 0.1913 - binary_accuracy: 0.9208
Epoch 9/30
 - 215s - loss: 0.1927 - binary_accuracy: 0.9203
Epoch 10/30
 - 219s - loss: 0.1926 - binary_accuracy: 0.9206
Epoch 11/30
 - 219s - loss: 0.1902 - binary_accuracy: 0.9210
Epoch 12/30
 - 219s - loss: 0.1892 - binary_accuracy: 0.9212
Epoch 13/30
 - 217s - loss: 0.1917 - binary_accuracy: 0.9204
Epoch 14/30
 - 217s - loss: 0.1932 - binary_accuracy: 0.9199
Epoch 15/30
 - 218s - loss: 0.1911 - binary_accuracy: 0.9208
Epoch 16/30
 - 218s - loss: 0.1885 - binary_accuracy: 0.9219
Epoch 17/30
 - 221s - loss: 0.191

KeyboardInterrupt: 

In [ ]:
model.predict(t, batch_size=32, verbose=0)

In [ ]:
del X_train

In [ ]:
df_test = pd.read_csv('./data/test.csv')
X_test = pd.read_csv('./test_with_prob.csv')
X_test = X_test.drop('Unnamed: 0', axis=1)
X_test['q1_q2_freq_diff'] = np.abs(X_test['q1_freq'] - X_test['q2_freq'])
X_test['q1_q2_freq_sum'] = X_test['q1_freq'] + X_test['q2_freq']
X_test['skew_diff'] = np.abs(X_test['skew_q1vec'] - X_test['skew_q2vec'])
X_test['skew_sum'] = X_test['skew_q1vec'] + X_train['skew_q2vec']

In [ ]:
X_test.replace(np.inf, 99)
X_test.replace(np.nan, 0)

In [ ]:
scaler.transform

In [ ]:
prob = model.predict(tr, verbose=0， batch_size=4096)

In [ ]:
sub = pd.DataFrame()
sub['test_id'] = df_test['test_id']
sub['is_duplicate'] = prob

In [ ]:
sub.head(10)

In [ ]:
sub.head(10)

In [ ]:

print('Saving :: submission file...')
sub.to_csv('subnn.csv', index=False)
print('\nSubmission result done.')